export enum Designation {
  MANAGER = "MANAGER",
  INGENIEUR = "INGENIEUR",
  ANALYSTE = "ANALYSTE",
  ADMINISTRATEUR = "ADMINISTRATEUR",
  SPECIALISTE = "SPECIALISTE",
  ASSISTANT = "ASSISTANT",
  DIRECTEUR = "DIRECTEUR",
  SUPERVISEUR = "SUPERVISEUR",
  CONSULTANT = "CONSULTANT",
  COORDONNATEUR = "COORDONNATEUR",
  TECHNICIEN = "TECHNICIEN",
  STAGIAIRE = "STAGIAIRE",
  CADRE = "CADRE",
  AGENT = "AGENT",
  CHEF_EQUIPE = "CHEF_EQUIPE",
  RESPONSABLE_RH = "RESPONSABLE_RH"
}
